### ISSUE TITLE
Deathwing subunit abilities

### ISSUE THREAD

**Issue by stuaroo** [tattersoftware/heroes-convert#2]
@MGatner I spent some time digging through the `heroes-convert` code (which I had only done a little since you first rolled this out, sorry I haven't been pulling my weight here at all!) and have a better idea of how things are working, but I ran into an interesting case with Deathwing and would like a second opinion.

For Deathwing's Form Switch (1), `heroes-talents` currently has the Destroyer form abilities on W and E but we haven't included the World Breaker form abilities (Lava Burst and Earth Shatter) anywhere.  That seemed like a pretty easy fix, just add subunit abilities, but when I did that I realized Deathwing has one other 'form': when he Z's you get two new abilities to specify which form to land in.  So now I'm wondering: should Deathwing have two additional sub-ability groups, one for World Breaker form and one for Dragonflight?  Or am I overthinking this and should just include all four abilities under something like DeathwingFormSwitch?  

By default the code currently pulls all four abilities under one subunit heading, so that would be the easy way to go.  I also can't think of another hero that this multiple forms would apply to, meaning it could be a bunch of extra work for minimal gain.

**Comment by MGatner** [comment]
I do remember seeing an issue report on Deathwing on `heroes-talents`. I’ve barely played him, but aren’t his Z abilities basically just “land in ______ form”? Unless you really want those or they have something I’m not remembering I’m in favor of leaving them out. I can take a closer look when I’m on desktop too. 

But thanks for looking over the concert code! Very open to any suggestions or improvements.

**Comment by stuaroo** [comment]
That's also what I thought the Z abilities would be before I saw the output.  There's actually a small amount of damage (who knew), a delay before landing, etc:

```
    {
        "uid": "7008f3",
        "name": "Destroyer",
        "description": "After 1.75 seconds, Deathwing slams down to the ground, dealing 50 (+4% per level) damage to enemies in the area and landing in Destroyer form. Deathwing can begin to cast Abilities 3 seconds after landing.",
        "hotkey": "Q",
        "abilityId": "Deathwing|Q2",
        "cooldown": 8,
        "icon": "storm_ui_icon_deathwing_destroyer.png",
        "type": "basic"
      },
      {
        "uid": "610108",
        "name": "World Breaker",
        "description": "After 1.75 seconds, Deathwing slams down to the ground, dealing 50 (+4% per level) damage to enemies in the area and landing in World Breaker form. Deathwing can begin to cast Abilities 3 seconds after landing.",
        "hotkey": "W",
        "abilityId": "Deathwing|W2",
        "cooldown": 8,
        "icon": "storm_ui_icon_deathwing_world_breaker.png",
        "type": "basic"
      }
```

**Comment by MGatner** [comment]
Oh yeah that looks worth having. If you have modifications yo the code to allow those please send a PR over and then we can update `heroes-talents`. Otherwise I will take a pass at this sometime this week. I need to address Samuro’s trait too
