### ISSUE TITLE
images-convert: rename and existing files

### ISSUE THREAD

**Issue by stuaroo** [tattersoftware/heroes-convert#4]
I finally got `images-convert` to work!  Someday I'll have to regale you with the tale of my frustrating struggle, but today I'm going to document this issue: running `images-convert` with the optional output directory and choosing a directory with existing images will cause files to not be renamed.

Ex: I ran `images-convert` and specified an output directory of my branch of heroes-talents/images/talents.  At the rename portion of the script, I received several messages like: 

`'/path/to/storm_ui_icon_kel'thuzad_chillingtouch.png' not renamed: '/path/to/storm_ui_icon_kelthuzad_chillingtouch.png' already exists`

This seems like an unexpected result, as my Kel'Thuzad images were not updated in the output location to have the correct name.

**Comment by MGatner** [comment]
Ah interesting, I might need to make sure it can overwrite or pre-remove existing files. I always start from scratch so had not run into this issue before.
